### ISSUE TITLE
Event markers above selected cellView

### ISSUE THREAD

**Issue by b3stia** [p-v/FlexibleCalendar#11]
Hi, 
I'am wondering how to make events markers always visible for now we have (look on 18):
![screenshot_2015-10-01-13-08-15](https://cloud.githubusercontent.com/assets/4069408/10219287/f71b0c5e-683d-11e5-8b8e-0d91fb265d9d.png)
![screenshot_2015-10-01-13-08-27](https://cloud.githubusercontent.com/assets/4069408/10219289/f9036642-683d-11e5-968b-cc5be296a64e.png)

But I want to have:
![screenshot_2015-10-01-13-08-27](https://cloud.githubusercontent.com/assets/4069408/10219322/363e9da6-683e-11e5-9024-60b443d27a04.png)

**Comment by p-v** [comment]
You can extend `BaseCellView` class. Use [ExampleCellView2](https://github.com/p-v/FlexibleCalendar/blob/master/app/src/main/java/com/p_v/flexiblecalendarexample/widget/ExampleCellView2.java) from the demo app. It should solve the issue for you. I haven't added it to the library so you will have to create the file in your project.
