### ISSUE TITLE
1st day of month is selected by default

### ISSUE THREAD

**Issue by prashant-webonise** [p-v/FlexibleCalendar#12]
Hi.
Nice library.
My problem is, the 1 day of month is shown selected by default and this occurs when the month is changed. I am not able to disable this. I dont want the 1st day of month to be shown selected. Am I missing something?

Also, I wish to have multiple date selections, for that purpose i added a clicklistener to getCellView but the clicklistener is not working.

**Comment by p-v** [comment]
Will patch this soon. There is a [branch](https://github.com/p-v/FlexibleCalendar/tree/auto-date-selection) in which the work is already under process. Its not stable currently. Not getting time to patch it, but it will come very soon.

**Comment by fncapps** [comment]
Same request here.
Thanks for the work.

**Comment by alex-marochko** [comment]
I need it too (disable 1st day autoselecting). Thank you!

**Comment by p-v** [comment]
I have pushed the changes to `develop` branch. You can use the version `1.2.0` for testing. Will release once it is stable.

**Comment by p-v** [comment]
Also, I have added a couple of methods,
- `getCurrentMonth`
- `getCurrentYear`

**Comment by alex-marochko** [comment]
@p-v , thank you very much! I can't explain why, this worked only when I placed
`calendarView.setDisableAutoDateSelection(true);` in `onMonthChange`.

**Comment by p-v** [comment]
@alex-marochko It should work even if you put it initially or inside the xml. If not then it might be a bug.

**Comment by alex-marochko** [comment]
@p-v tried xml first, with no effect. But your example is working right - I can't explain it.

**Comment by p-v** [comment]
Added the change to `1.2.1`.
