### ISSUE TITLE
Adding new types of "days"

### ISSUE THREAD

**Issue by twig** [p-v/FlexibleCalendar#13]
Looking at your values.xml, I saw state_dates such as REGULAR, TODAY, SELECTED, OUTSIDE_MONTH, etc, I was hoping to add a few new ones (such as PUBLIC HOLIDAY, etc).

Would it be sufficient to:

* Create my own declarable styles and add to CellState
* Not quite sure where to link the `EventDataProvider` to the cell generation.
* Check `int cellType` for CellState.PUBLIC_HOLIDAY during `FlexibleCalendarView.CalendarView.getCellView()` (or getWeekdayCellView()? I'm a little confused about the difference between the two)

Sorry if this has been asked before, but I was wondering what the most "correct" way of adding this would be.

**Comment by p-v** [comment]
I don't think PUBLIC_HOLIDAY should be added as a state. It's better to implement it using  `EventDataProvider` as it can be different for different scenarios.
