### ISSUE TITLE
SELECTED_TODAY does not set both states correctly

### ISSUE THREAD

**Issue by twig** [p-v/FlexibleCalendar#15]
case BaseCellView.TODAY:
                    cellView.addState(BaseCellView.STATE_TODAY);
                    break;
                case BaseCellView.SELECTED_TODAY:
                case BaseCellView.SELECTED:
                    cellView.addState(BaseCellView.STATE_SELECTED);
                    break;

**Comment by twig** [comment]
Patch in #16

**Comment by p-v** [comment]
There was a reason for this which I no longer remember but anyway thanks for the patch. :smiley:
