### ISSUE TITLE
Margin Around CellView?

### ISSUE THREAD

**Issue by mandrachek** [p-v/FlexibleCalendar#17]
I'm attempting to add margin around a cell view to let the background show through between each week row (tried both Square and EventCount CellView's), and it appears that the android:layout_margin values are not respected. Ideally I'd like to make it look something like https://github.com/p-v/FlexibleCalendar/blob/master/demo/screenshot-4.jpg, but with no horizontal margin between the days.

**Comment by p-v** [comment]
You can use `FlexibleCalendarView#setMonthViewHorizontalSpacing`/`FlexibleCalendarView#setMonthViewVerticalSpacing` for setting the spacing between the cell. 
If you wish to use it in xml, use `flex:monthDayHorizontalSpacing`

Set the `monthDayHorizontalSpacing` to 0. Hope that helps.
