### ISSUE TITLE
Issues with new Android support lib v23.2.0

### ISSUE THREAD

**Issue by Ammonious** [p-v/FlexibleCalendar#19]
There's a few issues I'm having with the new support library. First is when i perform   `calendarView.goToCurrentDay();` I get this error

`Process: PID: 27352 java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 10000, found: 402 Pager id: ffffffff Pager class: class com.p_v.flexiblecalendar.MonthViewPager Problematic adapter: class com.antonyt.infiniteviewpager.InfinitePagerAdapter`

The other issue I'm having is with `calendarView.refresh()` which doesn't seem to be working anymore. It was working flawlessly until the new support lib broke the world ;) JK, any help or updates would be most gratefully appreciated! 

To note as well when I page a few months to the right my events start to actually show in the calenderView. I'm not sure what to be looking for on this particular issue but I'm positive it's related to the new support library.

**Comment by twig** [comment]
Probably helpful to paste the full stacktrace.

(not flexiblecalendar dev but I'm not getting that issue with 23.2.0)

**Comment by p-v** [comment]
@Ammonious I'll look into it. Tried few cases and got the same error. 

@twig Looks like it's reproducible here. In case you want to have a look, I have pushed the error producing code to a new branch [support-lib-err](https://github.com/p-v/FlexibleCalendar/tree/support-lib-err). I just upgraded the library to android support library v23.2.0. `Calendar 1` in the demo gives the error. Ignore the back button in the first calendar.

**Comment by twig** [comment]
ahh interesting, thanks for the details.

**Comment by twig** [comment]
23.2.1 was just released

**Comment by p-v** [comment]
Yes, but the issue persists.

**Comment by AnwarShahriar** [comment]
I've started to use this library in my recent project. But this issue is crashing app every time. @p-v will it be possible to give a solution anytime soon? Btw great work

**Comment by p-v** [comment]
@AnwarShahriar 
Fixes are on their way. I have got most of the things working. I will push the changes in a couple of days.

**Comment by p-v** [comment]
The fix has been pushed. Feel free to post if any issues are found. 

@twig You might want to take look at this :smiley:

**Comment by twig** [comment]
> super.notifyDataSetChanged();

wow, so that's all it needed lol
nice find

**Comment by AnwarShahriar** [comment]
You're great man @p-v :+1:
