### ISSUE TITLE
Events as color cell

### ISSUE THREAD

**Issue by fncapps** [p-v/FlexibleCalendar#24]
Is it possible to have events shown as a different color cell? I mean, if you have standard blue cells for example, when you have an event, just paint the whole cell red.

Is it possible?

**EDIT**: I don't really need events, any way that makes possible to inflate each cell with a different layout based on the date will help.

**Comment by p-v** [comment]
You can extend `BaseCellView` and override `onDraw`. I have updated the demo app. Look out for Calendar 5.

**Comment by p-v** [comment]
Feel free to reopen if this wasn't what you were asking for :smiley:

**Comment by fncapps** [comment]
I don't really know how to do it >.<
Probably I explained wrong, I was trying to make some cells different from others maybe changing their background or just the full layout.
 Can you give me a more simple example?

**Comment by p-v** [comment]
Do you also want event circles on those cells? Do these different colors denote that the day has an event?

**Comment by fncapps** [comment]
I won't need event circles on those days.

The idea is not like having an event on those days but making different types of days.

For example, weekdays and weekends could have different colors to identify them quickly. Holidays could also have the weekend colors, etc...

**Comment by p-v** [comment]
Check the Calendar 3 in [example](https://github.com/p-v/FlexibleCalendar/tree/example) branch. I'm using the first event in the event list to determine the color of the background. You will have to build your own logic to determine weekends. Just pass the drawable/color using `EventDataProvider` interface in the first item of the list. Only the first item is considered. 

You will also have to implement your own custom BaseCellView as show in the example. In the `onDraw` of the custom cell you can play with the states. Like, what background has to be show if its a weekend and has been selected.

**Comment by fncapps** [comment]
I'll have a look at it when I have some time. Thanks for the help!

**Comment by p-v** [comment]
Sure. Feel free to post your queries. :smiley:

**Comment by fncapps** [comment]
Hi, I've been looking into your code. I have implemented the same code, without any logic, just fixed dates to try out if it is working.

I can see "events" highlighted but I cannot set the color to the whole cell_background... What I'm I missing?

**Comment by p-v** [comment]
What do you mean when you say you are able to see the events highlighted but you are not able to set the background? Are you using `EventBackgroundCellView` from the example?

**Comment by sanke-t** [comment]
@p-v can't seem to locate the example branch. If you could please provide the update URL.
