### ISSUE TITLE
Number of days in month when startDayOfTheWeek="MONDAY"

### ISSUE THREAD

**Issue by alex-marochko** [p-v/FlexibleCalendar#26]
Hi.
Lib is very helpful, but there's a bug: when `support:startDayOfTheWeek="MONDAY"`, then May 2016 shows only 27 days and only 26 for November 2015 (see screenshots). Thanks!
![device-2016-03-23-165040](https://cloud.githubusercontent.com/assets/15875712/13989109/9577328a-f117-11e5-92a4-8caafa6317ee.png)
![device-2016-03-23-165118](https://cloud.githubusercontent.com/assets/15875712/13989108/95768e0c-f117-11e5-8d65-035df9e910b7.png)

**Comment by p-v** [comment]
Happens when `showDatesOutsideMonth` is set to false, which is default.
