### ISSUE TITLE
the view doesnt refresh in API 23 android studio 2.0

### ISSUE THREAD

**Issue by JohanLight** [p-v/FlexibleCalendar#27]
after i update my android studio and change 
compile 'com.android.support:recyclerview-v7:23.3.0'
compile 'com.android.support:appcompat-v7:23.3.0'
when i use calendarview.refresh() it doesnt update the view. the events not appear in the calendar neither in the examples of the git.

**Comment by p-v** [comment]
Did you try version 1.2.1?

**Comment by MrPet** [comment]
Using FlexibleCalender version 1.2.1 solved it for me.
PS: great library!

**Comment by p-v** [comment]
@JohanLight I'm closing this issue. Feel free to reopen if you are still facing the issue.

**Comment by JohanLight** [comment]
Thanks. The problem was solved with the update
