### ISSUE TITLE
Calendar not showing date views.

### ISSUE THREAD

**Issue by nareshgunda-007** [p-v/FlexibleCalendar#28]
Calendar is showing only week labels view but not the date views. Im not getting where i have done wrong.

**Comment by p-v** [comment]
Can you please post your code?

**Comment by nareshgunda-007** [comment]
In xml preview it is showing properly but when i run on device dates are not visible. With zero code i'm able to reproduce the issue. Just using `com.p_v.flexiblecalendar.FlexibleCalendarView` in xml and launching the application giving the following ouptput. :(. 
![screen shot 2016-05-13 at 5 32 33 pm](https://cloud.githubusercontent.com/assets/19345502/15247282/cbea9014-1930-11e6-8bf7-6437451b31ca.png)

**Comment by p-v** [comment]
Are you using this inside a `ScrollView`? If so, you need to give it a fixed height.

**Comment by nareshgunda-007** [comment]
No, i'm not using this inside scrollview. The hierarchy is `CoordinatorLayout > LinearLayout > FrameLayout > (One Fragment with LinearLayout > com.p_v.flexiblecalendar.FlexibleCalendarView)`

**Comment by p-v** [comment]
Can you please post your xml which has this issue?

**Comment by nareshgunda-007** [comment]
Yeah, 

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <LinearLayout android:orientation="horizontal"
        android:background="@android:color/white"
        android:padding="5dp"
        android:gravity="center"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <ImageView android:id="@+id/left_arrow"
            android:src="@drawable/calender_left_arrow"
            android:layout_weight="1"
            android:layout_width="20dp"
            android:layout_height="40dp" />

        <TextView android:id="@+id/month_text_view"
            android:padding="5dp"
            android:gravity="center"
            android:textSize="22sp"
            android:textStyle="bold"
            android:textColor="@android:color/secondary_text_dark_nodisable"
            android:layout_width="wrap_content"
            android:layout_height="match_parent" />

        <ImageView android:id="@+id/right_arrow"
            android:src="@drawable/calender_right_arrow"
            android:layout_weight="1"
            android:layout_width="20dp"
            android:layout_height="40dp" />

        <ImageButton
            android:id="@+id/float_btn"
            android:text="Notify"
            android:layout_width="57dp"
            android:layout_height="40dp"
            android:src="@drawable/calender_noti_img" />

        <TextView
            android:id="@+id/alarm_noti"
            android:layout_width="wrap_content"
            android:layout_height="30dp"
            android:background="#689bf2"
            android:textStyle="bold"/>
    </LinearLayout>

    <com.p_v.flexiblecalendar.FlexibleCalendarView
        android:id="@+id/calendar_view"
        android:layout_width="match_parent"
        android:layout_height="300dip"
        android:layout_marginRight="30dip"
        android:layout_marginLeft="30dip"/>
</LinearLayout>
```

**Comment by nareshgunda-007** [comment]
I guess this issue is with the some specific hierarchy, when i used the above layout with separate activity dates are visible.

**Comment by p-v** [comment]
<?xml version="1.0" encoding="utf-8"?> 
    <android.support.design.widget.CoordinatorLayout tools:context="com.p_v.flexiblecalendarexample.CalendarActivity5"
    android:id="@+id/main_content"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:tools="http://schemas.android.com/tools">

    <LinearLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        xmlns:tools="http://schemas.android.com/tools">

        <LinearLayout android:orientation="horizontal"
            android:background="@android:color/white"
            android:padding="5dp"
            android:gravity="center"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <ImageView android:id="@+id/left_arrow"
                android:src="@drawable/left_arrow"
                android:layout_weight="1"
                android:layout_width="20dp"
                android:layout_height="40dp" />

            <TextView android:id="@+id/month_text_view"
                android:padding="5dp"
                android:gravity="center"
                android:textSize="22sp"
                android:textStyle="bold"
                android:textColor="@android:color/secondary_text_dark_nodisable"
                android:layout_width="wrap_content"
                android:layout_height="match_parent" />

            <ImageView android:id="@+id/right_arrow"
                android:src="@drawable/right_arrow"
                android:layout_weight="1"
                android:layout_width="20dp"
                android:layout_height="40dp" />

            <ImageButton
                android:id="@+id/float_btn"
                android:text="Notify"
                android:layout_width="57dp"
                android:layout_height="40dp"
                android:src="@drawable/left_arrow" />

            <TextView
                android:id="@+id/alarm_noti"
                android:layout_width="wrap_content"
                android:layout_height="30dp"
                android:background="#689bf2"
                android:textStyle="bold"/>
        </LinearLayout>

        <com.p_v.flexiblecalendar.FlexibleCalendarView
            android:id="@+id/calendar_view"
            android:background="@android:color/darker_gray"
            android:layout_height="wrap_content"
            android:layout_width="match_parent"
            android:layout_marginRight="30dip"
            android:layout_marginLeft="30dip"/>
    </LinearLayout>
    <android.support.design.widget.FloatingActionButton
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|right"
        android:layout_margin="16dp"
        android:src="@mipmap/ic_launcher"
        app:layout_anchorGravity="bottom|right|end"/>
    </android.support.design.widget.CoordinatorLayout>

This works fine for me. May be some other view is taking up the space in your hierarchy.

**Comment by nareshgunda-007** [comment]
Hi, the space is not occupying by any other layouts. For testing i've put some background colour and the output is proper. Im not able to understand why the date view are not visible in the specific hierarchy. Though it not dependent on hierarchy but im not able figure out the problem. Please help.

**Comment by p-v** [comment]
It would be very helpful if you could create a demo app for the issue. I'm not yet able to trace the issue.

**Comment by nareshgunda-007** [comment]
Hi, Yeah sure. P.F.A
[DemoCalendarApp.zip](https://github.com/p-v/FlexibleCalendar/files/267856/DemoCalendarApp.zip)

**Comment by p-v** [comment]
Setting `FlexibleCalendarView`'s height as match_parent works in your demo.

**Comment by p-v** [comment]
You may reopen the issue if you feel its still there.
