### ISSUE TITLE
Two text views in one cell.

### ISSUE THREAD

**Issue by itzluxman** [p-v/FlexibleCalendar#30]
Can we have two kinds of day in two different types of calendar format into one cell ??

it may look like this:

http://www.ashesh.com.np/images/Nepali-Calendar.png

**Comment by p-v** [comment]
Yes you can. 

Check [this example](https://github.com/p-v/FlexibleCalendar/blob/master/app/src/main/java/com/p_v/flexiblecalendarexample/CalendarActivity3.java). Create a class which implements `Event` interface just like the `CustomEvent` used with `FlexibleCalendarView#setEventDataProvider`. Just like the `color` inside the `CustomEvent` class you can add more fields, in your case, `String altText`.

Then, you need to override `BaseCellView`. Just like the [EventCountCellView](https://github.com/p-v/FlexibleCalendar/blob/master/library/src/main/java/com/p_v/flexiblecalendar/view/EventCountCellView.java).

You will have the `Event` list inside it which will be same as your `CustomEvent` list. You can use it to draw the desired view.

Feel free to reopen if you face any issues.

**Comment by itzluxman** [comment]
Thanks:)
