### ISSUE TITLE
Change Orientation

### ISSUE THREAD

**Issue by maicolreyes** [p-v/FlexibleCalendar#34]
on landscape mode is not showing the right height at MonthViewPager 
![screenshot_20160711-105108](https://cloud.githubusercontent.com/assets/3619051/16737121/840c267e-4755-11e6-82c2-fe662fac41e5.png)
![Uploading Screenshot_20160711-105132.png…]()

**Comment by p-v** [comment]
It should work if you specify some width in the landscape mode.

**Comment by p-v** [comment]
Feel free to reopen if you need further discussion over this.
