### ISSUE TITLE
Major Issue

### ISSUE THREAD

**Issue by arunramya** [p-v/FlexibleCalendar#41]
is not worked.. called lot of times  
calendarView.setEventDataProvider(new FlexibleCalendarView.EventDataProvider() {
            @Override
            public List<?extends CustomEvent> getEventsForTheDay(int ye, int mo, int da)
            {

**Comment by p-v** [comment]
Yes, because it is called for each cell in the view. It is used to tell if the cell with that particular `year, month, day` has any events or not.  

Read [here](https://gitter.im/p-v/FlexibleCalendar?at=56cee700dbccfd8a4fd05962) for more info
