### ISSUE TITLE
SetEventDataProvider

### ISSUE THREAD

**Issue by arunramya** [p-v/FlexibleCalendar#42]
calendarView.setEventDataProvider(new FlexibleCalendarView.EventDataProvider() {
            @Override
            public List<?extends CustomEvent> getEventsForTheDay(int ye, int mo, int da)
            {
              
                Log.e("Month", "" + mo);
                Log.e("Year", "" + ye);

                return null;
            }
        });

This run more than 500 times..

**Comment by p-v** [comment]
Please check #41
