### ISSUE TITLE
Dot not show  when  i  slected a day 

### ISSUE THREAD

**Issue by ajay91kukreja** [p-v/FlexibleCalendar#45]
Thanks for the  nice Library.
@Pratyush Verma
Can   you  tell  me when   we select  a day dot  not shown there ?
please help  me out

**Comment by p-v** [comment]
Can you please elaborate? Do you want to show the dot when the day is selected or do you want to hide it on selection?

**Comment by ajay91kukreja** [comment]
when  we select a day  i  want  to  show the dots

**Comment by p-v** [comment]
Check this issue.  #11

It should solve your problem.

**Comment by ajay91kukreja** [comment]
thanks
