### ISSUE TITLE
Change background color of dates

### ISSUE THREAD

**Issue by sanke-t** [p-v/FlexibleCalendar#46]
I want to change background color of multiple dates based on a few conditions, is this possible using your library?

**Comment by p-v** [comment]
You can achieve it by extending `BaseCellView`. 

Use `EventDataProvider` with a custom event for the day you want to set a different color.

```
calendarView.setEventDataProvider(new FlexibleCalendarView.EventDataProvider() {
    @Override
    public List<? extends Event> getEventsForTheDay(int year, int month, int day) {
        return getEventColorList(year,month,day);
    }
}); 
```
Checkout the `CirucularEventCellView` it extends `BaseCellView`. You can use the `onDraw` method to render the desired background for the day.

Unfortunately there isn't an easier way at present.
