### ISSUE TITLE
Event dot not show for today date and on day selected.

### ISSUE THREAD

**Issue by mabhim99** [p-v/FlexibleCalendar#48]
I am showing green dot for the event. But for the today date event dot is not showing.
Also when I select some date. then white background will display on date and dot disappear.

I want to know how to show event dot for the selected date and today date.

**Comment by p-v** [comment]
You will have to extend `BaseCellView`. This has been demonstrated in CalendarActivity2 in the demo, which uses [ExampleCellView2](https://github.com/p-v/FlexibleCalendar/blob/master/app/src/main/java/com/p_v/flexiblecalendarexample/widget/ExampleCellView2.java). This should solve the dot disappearing issue. Feel free to revert if you face any issues.
