### ISSUE TITLE
Event is not visible when selected

### ISSUE THREAD

**Issue by MihirPal** [p-v/FlexibleCalendar#5]
We have event on date 6th, it will display event bullet but when we select 6th only background color will get displayed. Is there any method to show event on selected date?

![1](https://cloud.githubusercontent.com/assets/10336559/9463948/d1e6a32a-4b3d-11e5-8f5f-d82322fc2e0e.png)

![2](https://cloud.githubusercontent.com/assets/10336559/9463951/d99c4f66-4b3d-11e5-92f6-693ab2f0860b.png)

**Comment by p-v** [comment]
I have not currently added it to the default `SquareCellView`, but you can extend the `BaseCellView` and override the two methods `onSizeChange` and `onDraw`. The check [here](https://github.com/p-v/FlexibleCalendar/blob/master/library/src/main/java/com/p_v/flexiblecalendar/view/CircularEventCellView.java#L59) and [here](https://github.com/p-v/FlexibleCalendar/blob/master/library/src/main/java/com/p_v/flexiblecalendar/view/CircularEventCellView.java#L89) are preventing you to display the events on selection. You can implement it in a similar way like I have done for `EventCountCellView` [here](https://github.com/p-v/FlexibleCalendar/blob/master/library/src/main/java/com/p_v/flexiblecalendar/view/EventCountCellView.java#L65). The events are displayed even if the user has selected the cell. Let me know if you face any issues.

**Comment by p-v** [comment]
@MihirPal I have added updated the demo app. Check out the [CalendarActivity2](https://github.com/p-v/FlexibleCalendar/blob/eca8a6475ec2a167d5339e384255140f4aaa3a20/app/src/main/java/com/p_v/flexiblecalendarexample/CalendarActivity2.java), here I'm using a [ExampleCellView2](https://github.com/p-v/FlexibleCalendar/blob/eca8a6475ec2a167d5339e384255140f4aaa3a20/app/src/main/java/com/p_v/flexiblecalendarexample/widget/ExampleCellView2.java) which is extended from `BaseCellView`. This will show the events in all the states, event if selected. 

I haven't included this in the library as there can be several other customized cells which will unnecessarily bloat the library. Feel free to reopen the issue if you face any problem.
