### ISSUE TITLE
wrap_content on FlexibleCalendarView

### ISSUE THREAD

**Issue by badadin** [p-v/FlexibleCalendar#52]
If the layout is:

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical">

    <com.p_v.flexiblecalendar.FlexibleCalendarView
        android:id="@+id/flexibleCalendarView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@android:color/darker_gray"/>

    ...

</LinearLayout>
```

It looks like:

![0](https://cloud.githubusercontent.com/assets/23579911/23698774/45b824fe-0406-11e7-9ae9-5901c05bc34d.png)

But if I wrap it into ScrollView:

```
<ScrollView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
            
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">
        
        <com.p_v.flexiblecalendar.FlexibleCalendarView
            android:id="@+id/flexibleCalendarView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@android:color/white"/>
        
        ...

    </LinearLayout>

</ScrollView>
```

It looks like:

![1](https://cloud.githubusercontent.com/assets/23579911/23698795/5dbbf3aa-0406-11e7-8e2f-c86e0f3dc159.png)

How can I prevent this issue without setting absolute size in dp to FlexibleCalendarView?

**Comment by p-v** [comment]
Add `android:fillViewport="true"`  to your `ScrollView`. It should work.

**Comment by badadin** [comment]
Exactly! Absolutely forgot about this property. Thank you very much!

**Comment by savvisingh** [comment]
I tried that in my Scrollview with another layout but got no success
`<android.support.v4.widget.NestedScrollView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@id/top_header"
            android:layout_above="@+id/adView"
            android:fillViewport="true"
            android:id="@+id/scrollView">

            <RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

                <com.p_v.flexiblecalendar.FlexibleCalendarView
                    android:id="@+id/calendar_view"
                    android:background="@android:color/transparent"
                    android:layout_height="wrap_content"
                    android:layout_width="match_parent"
                    />

                <android.support.v7.widget.RecyclerView
                    android:layout_below="@id/calendar_view"
                    android:layout_margin="8dp"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:id="@+id/monthEventList"
                    android:visibility="visible"/>

            </RelativeLayout>

        </android.support.v4.widget.NestedScrollView>`

It renders correctly in layout preview but when I run the app it hides the calender
