### ISSUE TITLE
Populate event on calendar load - how to get start and end date 

### ISSUE THREAD

**Issue by Nidhee** [p-v/FlexibleCalendar#58]
Hello,

Firstly thank you for awesome calendar view.

I want to populate list of events when a calendar is load, for that I need start and end date of calendar visible. How can I get that. ?

**Comment by p-v** [comment]
```
calendarView.setEventDataProvider(new FlexibleCalendarView.EventDataProvider() {
    @Override
    public List<? extends Event> getEventsForTheDay(int year, int month, int day) {
        // Add your logic here
        return getEventColorList(year,month,day);
    }
});
```

Use this method to set the events it will be called for each day.
