### ISSUE TITLE
Date selected remains persistent on month change. 

### ISSUE THREAD

**Issue by Nidhee** [p-v/FlexibleCalendar#61]
Hello,

Once a date is selected, it remains selected on month change also. I have disable auto date selection in xml: disableAutoDateSelection.

If I am selecting a date for example - 11/08/2017, on month change it keeps 11th date selected for other months too. How to remove that selection.

**Comment by p-v** [comment]
@Nidhee 
Works for me. Can you please post your code?

**Comment by Nidhee** [comment]
Here is my code:
`private void configureCalendar(){

        calendarView.setCalendarView(new FlexibleCalendarView.CalendarView() {
            @Override
            public BaseCellView getCellView(int position, View convertView, ViewGroup parent, @BaseCellView.CellType int cellType) {
                BaseCellView cellView = (BaseCellView) convertView;
                if (cellView == null) {
                    LayoutInflater inflater = LayoutInflater.from(getActivity());
                    cellView = (BaseCellView) inflater.inflate(R.layout.event_calendar_date_cell_view, null);
                }
               
                return cellView;
            }

            @Override
            public BaseCellView getWeekdayCellView(int position, View convertView, ViewGroup parent) {
                BaseCellView cellView = (BaseCellView) convertView;
                if (cellView == null) {
                    LayoutInflater inflater = LayoutInflater.from(getActivity());
                    cellView = (BaseCellView) inflater.inflate(R.layout.event_calendar_week_cell_view, null);
                }

                return cellView;
            }

            @Override
            public String getDayOfWeekDisplayValue(int dayOfWeek, String defaultValue) {
                return null;
            }
        });
        calendarView.setOnMonthChangeListener(this);
        calendarView.setOnDateClickListener(this);
    }`
On onMonthChange I am calling new calling new API,

**Comment by p-v** [comment]
This looks ok. What are you doing on month change? Have you tried debugging the calendar by commenting out `OnMonthChange` call.

**Comment by Nidhee** [comment]
When I commented everything on `OnMonthChange `, no date is selected.

**Comment by p-v** [comment]
There will always be one date selected, the default selected date is the today's date.

**Comment by p-v** [comment]
Closing this issue as it won't fix. One date will always remain selected. Feel free to send any pull request.
