### ISSUE TITLE
How can I setEvent on current day?

### ISSUE THREAD

**Issue by GeneHsieh** [p-v/FlexibleCalendar#63]
I wrote like this
````
private void fillEvents() {
        mFCVEventCalendar.setEventDataProvider(new FlexibleCalendarView.EventDataProvider() {
            @Override
            public List<com.p_v.flexiblecalendar.entity.CalendarEvent> getEventsForTheDay(int year, int month, int day) {

                if (year == 2017/*calendar.get(Calendar.YEAR)*/ && month == 8/*calendar.get(Calendar.MONTH)*/ && day == 7/*calendar.get(Calendar.DAY_OF_MONTH)*/) {
                    List<com.p_v.flexiblecalendar.entity.CalendarEvent> eventColors = new ArrayList<>(2);
                    eventColors.add(new com.p_v.flexiblecalendar.entity.CalendarEvent(android.R.color.holo_blue_light));
                    eventColors.add(new com.p_v.flexiblecalendar.entity.CalendarEvent(android.R.color.holo_purple));
                    System.out.println("date :" + year + month + day);
                    return eventColors;
                }
return null;
}
});
    }
````

and today is 2017/9/7 
I hope can show the event of current day
How can I do?

**Comment by p-v** [comment]
This looks correct to me. What is the issue you are facing?

**Comment by GeneHsieh** [comment]
today(2017/9/8) I can see the event dot on 2017/9/7, but yesterday the event dot can't show.
This is today's photo
![device-2017-09-08-141935](https://user-images.githubusercontent.com/5857361/30198613-28615052-94a1-11e7-84ee-2ed08fdaca3f.png)

This is what I saw yesterday
![screenshot_2017-09-07-14-25-35](https://user-images.githubusercontent.com/5857361/30198767-0e2f8932-94a2-11e7-936a-513cb2d30ff4.png)

Is any config I didn't set up while the state is TODAY ?

**Comment by p-v** [comment]
That may be because its the current day. You can extend the `BaseCellView` class to show events for the current day. Its there in one of the examples.

**Comment by p-v** [comment]
Check [this class](https://github.com/p-v/FlexibleCalendar/blob/master/app/src/main/java/com/p_v/flexiblecalendarexample/widget/ExampleCellView2.java)
