### ISSUE TITLE
Event color issue

### ISSUE THREAD

**Issue by DevItAndroidTeam** [p-v/FlexibleCalendar#65]
Hello,
I am facing problem in event color change issue on selection of date.
Can you please help me how to change color of event text on date selection?

**Comment by p-v** [comment]
You can use a customized `BaseCellView` and override the `onDraw` method. Check the `CalendarActivity2` it uses [ExampleCellView2](https://github.com/p-v/FlexibleCalendar/blob/master/app/src/main/java/com/p_v/flexiblecalendarexample/widget/ExampleCellView2.java), it should solve your problem.
