### ISSUE TITLE
FlexibleCalendarView in ScrollView or ListView

### ISSUE THREAD

**Issue by android-x64** [p-v/FlexibleCalendar#7]
Hi. Nice calendar. But I can't use it in ScrollView or ListView. It shows just days of week

**Comment by p-v** [comment]
You will have to give `FlexibleCalendarView` a fixed height in order to use it inside `ScrollView`.

**Comment by android-x64** [comment]
Thanks!

**Comment by luongvo** [comment]
I still meet this issue. Is it resolved?

**Comment by p-v** [comment]
@luongvo Did you try to give `FlexibleCalendarView` a fixed height? Giving `FlexibleCalendarView` a fixed height should resolve your issue. If you are still facing the issue feel free to reopen.
