### ISSUE TITLE
Can't  use "for"on calendarView.setEventDataProvider

### ISSUE THREAD

**Issue by telmoxp1** [p-v/FlexibleCalendar#9]
When I try to use the " for " to put in  several days with events , does not work.
 For example:

calendarView.setEventDataProvider(new FlexibleCalendarView.EventDataProvider() {
            @Override
            public List<? extends Event> getEventsForTheDay(int year, int month, int day) {
                return getEventColorList(year, month, day);
            }

            private List<? extends Event> getEventColorList(int year, int month, int day) {
                int sdf;
               do {
                    int joka = 0;
                    for (int jbf = 0; jbf < m_parts.size(); jbf++) {
                        if (datameio.getTime().after(m_parts.get(jbf).getDataInicio()) && datameio.getTime().before(m_parts.get(jbf).getDataFim()) || datameio.getTime().equals(m_parts.get(jbf).getDataInicio()) && datameio.getTime().before(m_parts.get(jbf).getDataFim()) || datameio.getTime().after(m_parts.get(jbf).getDataInicio()) && datameio.getTime().equals(m_parts.get(jbf).getDataFim())) {
                            joka++;
                        }
                    }
                    List<CalendarEvent> eventColors = new ArrayList<>();
                    int ano = datameio.get(Calendar.YEAR);
                    int mes =datameio.get(Calendar.MONTH);
                    int dia =datameio.get(Calendar.DAY_OF_MONTH);
                    if (year ==ano && month == mes && day ==dia ) {
                       for (int i = 0; i < joka; i++) {
                        eventColors.add(new CalendarEvent(android.R.color.holo_purple));
                        }

                        return eventColors;
                }
                datameio.add(Calendar.DATE, 1);
            } while (datameio.before(datamaistarde));

                return null;

            }
        });

**Comment by telmoxp1** [comment]
Pls help me xD ty

**Comment by p-v** [comment]
This should work normally. If you are updating `datameio` or `m_parts`, then call `FlexibleCalendarView#refresh()` whenever you change them so that the changes are reflected in the currently visible view.

If that doesn't solve, can you please fork and update the demo in the forked repo reproducing the issue?

**Comment by telmoxp1** [comment]
The issue continues

**Comment by p-v** [comment]
Can you write a small test that reproduce the issue in the demo app?

**Comment by telmoxp1** [comment]
Put this code in Calendar 3 or 4 , in calendar 1 it works fine.

 calendarView.setEventDataProvider(new FlexibleCalendarView.EventDataProvider() {
            @Override
            public List<CalendarEvent> getEventsForTheDay(int year, int month, int day) {
                Calendar kalendar= Calendar.getInstance() ;
                for (int i=0;i<=10;i++) {
                    if (year == kalendar.get(Calendar.YEAR) && month == kalendar.get(Calendar.MONTH) && day == kalendar.get(Calendar.DATE)) {
                        List<CalendarEvent> eventColors = new ArrayList<>();
                        for (int ib = 0; ib <= 10; ib++) {
                            eventColors.add(new CalendarEvent(android.R.color.holo_red_dark));
                        }
                        return eventColors;
                    }
                    kalendar.add(Calendar.DATE,1);
               }
                return null;
            }
        });

**Comment by telmoxp1** [comment]
if you change the "for" for an specific Date it will work fine

**Comment by p-v** [comment]
I added the following,

    calendarView.setEventDataProvider(new FlexibleCalendarView.EventDataProvider() {
            @Override
            public List<? extends Event> getEventsForTheDay(int year, int month, int day) {
                Calendar kalendar= Calendar.getInstance() ;
                for (int i=0;i<=10;i++) {
                    if (year == kalendar.get(Calendar.YEAR) && month == kalendar.get(Calendar.MONTH) && day == kalendar.get(Calendar.DATE)) {
                        List eventColors = new ArrayList<>();
                        for (int ib = 0; ib <= 10; ib++) {
                            eventColors.add(new CalendarEvent(android.R.color.holo_red_dark));
                        }
                        return eventColors;
                    }
                    kalendar.add(Calendar.DATE,1);
                }
                return null;
            }
        });

It gave me, 
<img width="417" alt="screen shot 2015-09-16 at 7 35 00 pm" src="https://cloud.githubusercontent.com/assets/11094504/9906875/135552d4-5caa-11e5-9912-be3b8365391f.png">

What are you expecting? It will be helpful if you can explain me your use case.

**Comment by telmoxp1** [comment]
Have An Event List and quandovou for the calendar is supposed to show him every day how many events have for each day.

**Comment by p-v** [comment]
Do you want to show the count or the events as shown in the first calendar demo?

**Comment by telmoxp1** [comment]
the count

**Comment by p-v** [comment]
join https://gitter.im/p-v/FlexibleCalendar

**Comment by p-v** [comment]
Feel free to reopen in case you issue is not resolved.
